algorithm:
  n: [1, 3, 5, 7]
  lr:
    - 5.0e-03
    - 1.0e-03
    - 5.0e-04
    - 1.0e-04
    - 5.0e-05
    - name: linear
      start: 5.0e-03
      step: -1.0e-08
      end: 5.0e-05
  eps:
    - 0.1
    - 0.05
    - 0.01
    - name: linear
      start: 0.1
      step: -0.000001
      end: 0.01
    
features:
  tiles_no: [8, 16]
      
