title: State-aggregation for 1000-state random walk
environment: MountainCar-v0
episodes: 10000
gamma: 0.99
features:
  name: tilings
  bins_no: 8
algorithms:
  - name: lstd
    eps: .00001
  - name: lstd
    eps: .0001
  - name: lstd
    eps: .001
  - name: lstd
    eps: .01
  - name: lstd
    eps: .1
  - name: lstd
    eps: 1
  - name: lstd
    eps: 10
