title: State-aggregation for 1000-state random walk
environment: thousand-states
episodes: 100000
gamma: 0.99
features:
  name: state-aggregation
  bins_no: 10
algorithms:
  - name: lstd
    eps: .001
  - name: gtd
    n: 1
    lr: .00002
  - name: gtd
    n: 5
    lr: .00002
  - name: gtd
    n: 10
    lr: .00002
  - name: gmc
    lr: .00002
  - name: gtd
    n: 1
    lr: .0002
  - name: gmc
    lr: .0002
